#!/bin/bash
#Küsin kasutajalt vanust
echo "Palun sisestage oma vanus."

read vanus
#Viin läbi vastavad IF loosungid
if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "Te olete laps."
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "Olete nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
	echo "Olete täiskasvanu"
elif test $vanus -ge 63
then
	echo "Olete senioor"
else
#loon veateate tooriku sõnumi
	echo "Palun sisestage korrektne väljund"
fi

