#!/bin/bash

echo -n "Sisestage kuu number:"

read number

if test $number -gt 0 -a $number -lt 3 -o $number -eq 12

then
	echo "On talv"
elif test $number -ge 3 -a $number -lt 6
then
	echo "On kevad"
elif test $number -ge 6 -a $number -lt 9
then
	echo "On suvi"
elif test $number -ge 9 -a $number -lt 12
then
	echo "On sügis"
fi
