#!/bin/bash

echo -n "Palun sisestage aja väärtus:"
read aeg

if test $aeg -gt 5 -a $aeg -lt 12
then
echo	"Tere hommikust, $USER"
elif test $aeg -gt 12 -a $aeg -lt 18
then
echo	"Tere päevast, $USER"
elif test $aeg -gt 17 -a $aeg -lt 22
then
echo	"Tere õhtust, $USER"
elif test $aeg -gt 22 -a $aeg -lt 25 -o $aeg -gt 0 -a $aeg -lt 6
then
echo	"Head ööd, $USER"
fi
