#!/bin/bash
#Tervitusskript koos veidike suhkruga.

# echo "Tere User!"
echo "Tere "
echo -n `who am i | cut -c1 | tr [:lower:] [:upper:]`
echo -n `who am i | cut -c2-` #lõika tähed alates 2-st
echo "!"
