#!/bin/bash

#Küsin echo kaudu kasutajalt tema nime
echo "Tere, palun sisestage oma nimi"

#Ootab sisestust kasutajalt
read eesnimi perenimi

#Kui sisestus kasutajalt saadud, väljastab selle Tere, $varname abil
echo "Tere, eesnimi on $eesnimi ja perenimi $perenimi"

