#!/bin/bash

for ((r=1; r<=5;r++))
do
	echo -n "$r "
	if [ $r -eq 1 ]; then



	for ((b = 1; b <= 5; b++))
	do
	echo -n "* "
	done
	else
	echo -n "* "

	for ((a = 2; a < 5; a++))
	do
	echo -n "  "
	done
	echo -n "* "
	fi
	echo
done
